name: Go

on:
  push:
    branches:
      - develop
      - master
      - staging
      - trying
      - v2
  pull_request:
    branches:
      - develop
      - master
      - v2

jobs:

  build:
    strategy:
      matrix:
        include:
          - go: 'oldstable'
            goarch: amd64
            runs-on: ubuntu-latest
          - go: 'stable'
            goarch: amd64
            runs-on: ubuntu-latest
          - go: 'stable'
            goarch: '386'
            runs-on: ubuntu-latest
          - go: 'stable'
            goarch: arm64
            runs-on: ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Set up GOARCH
      run: export GOARCH="${{ matrix.goarch }}"

    - name: Build
      run: go build -v ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest

    - name: Test
      run: go test -v ./...

  # Added to summarize the matrix (otherwise we would need to list every single
  # job in bors.toml)
  # thanks https://forum.bors.tech/t/bors-with-github-workflows/426/4
  tests-result:
    name: Tests result
    if: always()
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as a success
        if: needs.build.result == 'success'
        run: exit 0
      - name: Mark the job as a failure
        if: needs.build.result == 'failure'
        run: exit 1
